/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GCardcrollPane = new javax.swing.JScrollPane();
        GCardPanel1 = new javax.swing.JPanel();
        GCardCartRow1 = new javax.swing.JButton();
        GCardRateRow1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jGCardTable = new javax.swing.JTable();
        GCardCartRow2 = new javax.swing.JButton();
        GCardCartRow3 = new javax.swing.JButton();
        GCardCartRow4 = new javax.swing.JButton();
        GCardCartRow5 = new javax.swing.JButton();
        GCardCartRow6 = new javax.swing.JButton();
        GCardCartRow7 = new javax.swing.JButton();
        GCardCartRow8 = new javax.swing.JButton();
        GCardCartRow9 = new javax.swing.JButton();
        GCardCartRow10 = new javax.swing.JButton();
        GCardCartRow11 = new javax.swing.JButton();
        GCardCartRow12 = new javax.swing.JButton();
        GCardCartRow13 = new javax.swing.JButton();
        GCardCartRow14 = new javax.swing.JButton();
        GCardCartRow15 = new javax.swing.JButton();
        GCardCartRow16 = new javax.swing.JButton();
        GCardCartRow17 = new javax.swing.JButton();
        GCardCartRow18 = new javax.swing.JButton();
        GCardCartRow19 = new javax.swing.JButton();
        GCardCartRow20 = new javax.swing.JButton();
        GCardCartRow21 = new javax.swing.JButton();
        GCardCartRow22 = new javax.swing.JButton();
        GCardCartRow23 = new javax.swing.JButton();
        GCardRateRow2 = new javax.swing.JButton();
        GCardRateRow3 = new javax.swing.JButton();
        GCardRateRow4 = new javax.swing.JButton();
        GCardRateRow5 = new javax.swing.JButton();
        GCardRateRow6 = new javax.swing.JButton();
        GCardRateRow7 = new javax.swing.JButton();
        GCardRateRow8 = new javax.swing.JButton();
        GCardRateRow9 = new javax.swing.JButton();
        GCardRateRow10 = new javax.swing.JButton();
        GCardRateRow11 = new javax.swing.JButton();
        GCardRateRow12 = new javax.swing.JButton();
        GCardRateRow13 = new javax.swing.JButton();
        GCardRateRow14 = new javax.swing.JButton();
        GCardRateRow15 = new javax.swing.JButton();
        GCardRateRow16 = new javax.swing.JButton();
        GCardRateRow17 = new javax.swing.JButton();
        GCardRateRow18 = new javax.swing.JButton();
        GCardRateRow19 = new javax.swing.JButton();
        GCardRateRow20 = new javax.swing.JButton();
        GCardRateRow21 = new javax.swing.JButton();
        GCardRateRow22 = new javax.swing.JButton();
        GCardRateRow23 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GCardcrollPane.setBackground(new java.awt.Color(172, 172, 172));
        GCardcrollPane.setForeground(new java.awt.Color(172, 172, 172));

        GCardPanel1.setBackground(new java.awt.Color(172, 172, 172));

        GCardCartRow1.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow1ActionPerformed(evt);
            }
        });

        GCardRateRow1.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow1ActionPerformed(evt);
            }
        });

        jGCardTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jGCardTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Chipset", "Graphics Engine Model", "Interface Bus (PCI Express)", "Memory (GB)", "PSU (W)", "Price (Tk)", "Rating"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jGCardTable.setGridColor(new java.awt.Color(204, 204, 204));
        jGCardTable.setSelectionBackground(new java.awt.Color(137, 180, 177));
        jGCardTable.getTableHeader().setResizingAllowed(false);
        jGCardTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jGCardTable);
        if (jGCardTable.getColumnModel().getColumnCount() > 0) {
            jGCardTable.getColumnModel().getColumn(0).setResizable(false);
            jGCardTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            jGCardTable.getColumnModel().getColumn(1).setResizable(false);
            jGCardTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            jGCardTable.getColumnModel().getColumn(2).setResizable(false);
            jGCardTable.getColumnModel().getColumn(2).setPreferredWidth(150);
            jGCardTable.getColumnModel().getColumn(3).setResizable(false);
            jGCardTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            jGCardTable.getColumnModel().getColumn(5).setResizable(false);
            jGCardTable.getColumnModel().getColumn(6).setResizable(false);
            jGCardTable.getColumnModel().getColumn(7).setResizable(false);
        }

        GCardCartRow2.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow2ActionPerformed(evt);
            }
        });

        GCardCartRow3.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow3ActionPerformed(evt);
            }
        });

        GCardCartRow4.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow4ActionPerformed(evt);
            }
        });

        GCardCartRow5.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow5ActionPerformed(evt);
            }
        });

        GCardCartRow6.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow6ActionPerformed(evt);
            }
        });

        GCardCartRow7.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow7ActionPerformed(evt);
            }
        });

        GCardCartRow8.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow8ActionPerformed(evt);
            }
        });

        GCardCartRow9.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow9ActionPerformed(evt);
            }
        });

        GCardCartRow10.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow10ActionPerformed(evt);
            }
        });

        GCardCartRow11.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow11ActionPerformed(evt);
            }
        });

        GCardCartRow12.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow12ActionPerformed(evt);
            }
        });

        GCardCartRow13.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow13ActionPerformed(evt);
            }
        });

        GCardCartRow14.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow14ActionPerformed(evt);
            }
        });

        GCardCartRow15.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow15ActionPerformed(evt);
            }
        });

        GCardCartRow16.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow16ActionPerformed(evt);
            }
        });

        GCardCartRow17.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow17ActionPerformed(evt);
            }
        });

        GCardCartRow18.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow18ActionPerformed(evt);
            }
        });

        GCardCartRow19.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow19ActionPerformed(evt);
            }
        });

        GCardCartRow20.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow20ActionPerformed(evt);
            }
        });

        GCardCartRow21.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow21ActionPerformed(evt);
            }
        });

        GCardCartRow22.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow22ActionPerformed(evt);
            }
        });

        GCardCartRow23.setBackground(new java.awt.Color(137, 180, 177));
        GCardCartRow23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SmallCart.png"))); // NOI18N
        GCardCartRow23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardCartRow23ActionPerformed(evt);
            }
        });

        GCardRateRow2.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow2ActionPerformed(evt);
            }
        });

        GCardRateRow3.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow3ActionPerformed(evt);
            }
        });

        GCardRateRow4.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow4ActionPerformed(evt);
            }
        });

        GCardRateRow5.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow5ActionPerformed(evt);
            }
        });

        GCardRateRow6.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow6ActionPerformed(evt);
            }
        });

        GCardRateRow7.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow7ActionPerformed(evt);
            }
        });

        GCardRateRow8.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow8ActionPerformed(evt);
            }
        });

        GCardRateRow9.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow9ActionPerformed(evt);
            }
        });

        GCardRateRow10.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow10ActionPerformed(evt);
            }
        });

        GCardRateRow11.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow11ActionPerformed(evt);
            }
        });

        GCardRateRow12.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow12ActionPerformed(evt);
            }
        });

        GCardRateRow13.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow13ActionPerformed(evt);
            }
        });

        GCardRateRow14.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow14ActionPerformed(evt);
            }
        });

        GCardRateRow15.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow15ActionPerformed(evt);
            }
        });

        GCardRateRow16.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow16ActionPerformed(evt);
            }
        });

        GCardRateRow17.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow17ActionPerformed(evt);
            }
        });

        GCardRateRow18.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow18ActionPerformed(evt);
            }
        });

        GCardRateRow19.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow19ActionPerformed(evt);
            }
        });

        GCardRateRow20.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow20ActionPerformed(evt);
            }
        });

        GCardRateRow21.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow21ActionPerformed(evt);
            }
        });

        GCardRateRow22.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow22ActionPerformed(evt);
            }
        });

        GCardRateRow23.setBackground(new java.awt.Color(137, 180, 177));
        GCardRateRow23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Star.png"))); // NOI18N
        GCardRateRow23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GCardRateRow23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GCardPanel1Layout = new javax.swing.GroupLayout(GCardPanel1);
        GCardPanel1.setLayout(GCardPanel1Layout);
        GCardPanel1Layout.setHorizontalGroup(
            GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GCardPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(GCardRateRow23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addComponent(GCardCartRow17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardRateRow17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        GCardPanel1Layout.setVerticalGroup(
            GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GCardPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                    .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                            .addGroup(GCardPanel1Layout.createSequentialGroup()
                                                                                                                                                                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                                                                                    .addComponent(GCardRateRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                                                                    .addComponent(GCardCartRow1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                                .addComponent(GCardCartRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                            .addComponent(GCardRateRow2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                        .addComponent(GCardCartRow3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                    .addComponent(GCardRateRow3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                                .addComponent(GCardCartRow4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                            .addComponent(GCardRateRow4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                        .addComponent(GCardCartRow5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                    .addComponent(GCardRateRow5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                .addComponent(GCardCartRow6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                            .addComponent(GCardRateRow6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                        .addComponent(GCardCartRow7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                    .addComponent(GCardRateRow7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                .addComponent(GCardCartRow8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                            .addComponent(GCardRateRow8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addComponent(GCardCartRow9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                    .addComponent(GCardRateRow9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                .addComponent(GCardCartRow10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                            .addComponent(GCardRateRow10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addComponent(GCardCartRow11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                    .addComponent(GCardRateRow11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(GCardCartRow12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addComponent(GCardRateRow12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(GCardCartRow13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addComponent(GCardRateRow13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(GCardCartRow14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(GCardRateRow14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(GCardCartRow15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(GCardRateRow15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(GCardCartRow16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(GCardRateRow16, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GCardCartRow17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GCardRateRow17, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GCardCartRow18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GCardRateRow18, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(GCardCartRow19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GCardRateRow19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(GCardCartRow20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(GCardRateRow20, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GCardCartRow21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(GCardRateRow21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GCardCartRow22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(GCardRateRow22, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GCardPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GCardCartRow23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GCardRateRow23, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GCardPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        GCardcrollPane.setViewportView(GCardPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GCardcrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GCardcrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 727, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GCardCartRow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow1ActionPerformed
        
    }//GEN-LAST:event_GCardCartRow1ActionPerformed

    private void GCardRateRow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow1ActionPerformed
        
        
    }//GEN-LAST:event_GCardRateRow1ActionPerformed

    private void GCardCartRow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow2ActionPerformed

    private void GCardCartRow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow3ActionPerformed

    private void GCardCartRow4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow4ActionPerformed

    private void GCardCartRow5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow5ActionPerformed

    private void GCardCartRow6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow6ActionPerformed

    private void GCardCartRow7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow7ActionPerformed

    private void GCardCartRow8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow8ActionPerformed

    private void GCardCartRow9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow9ActionPerformed

    private void GCardCartRow10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow10ActionPerformed

    private void GCardCartRow11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow11ActionPerformed

    private void GCardCartRow12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow12ActionPerformed

    private void GCardCartRow13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow13ActionPerformed

    private void GCardCartRow14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow14ActionPerformed

    private void GCardCartRow15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow15ActionPerformed

    private void GCardCartRow16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow16ActionPerformed

    private void GCardCartRow17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow17ActionPerformed

    private void GCardCartRow18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow18ActionPerformed

    private void GCardCartRow19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow19ActionPerformed

    private void GCardCartRow20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow20ActionPerformed

    private void GCardCartRow21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow21ActionPerformed

    private void GCardCartRow22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow22ActionPerformed

    private void GCardCartRow23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardCartRow23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardCartRow23ActionPerformed

    private void GCardRateRow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow2ActionPerformed

    private void GCardRateRow3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow3ActionPerformed

    private void GCardRateRow4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow4ActionPerformed

    private void GCardRateRow5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow5ActionPerformed

    private void GCardRateRow6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow6ActionPerformed

    private void GCardRateRow7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow7ActionPerformed

    private void GCardRateRow8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow8ActionPerformed

    private void GCardRateRow9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow9ActionPerformed

    private void GCardRateRow10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow10ActionPerformed

    private void GCardRateRow11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow11ActionPerformed

    private void GCardRateRow12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow12ActionPerformed

    private void GCardRateRow13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow13ActionPerformed

    private void GCardRateRow14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow14ActionPerformed

    private void GCardRateRow15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow15ActionPerformed

    private void GCardRateRow16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow16ActionPerformed

    private void GCardRateRow17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow17ActionPerformed

    private void GCardRateRow18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow18ActionPerformed

    private void GCardRateRow19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow19ActionPerformed

    private void GCardRateRow20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow20ActionPerformed

    private void GCardRateRow21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow21ActionPerformed

    private void GCardRateRow22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow22ActionPerformed

    private void GCardRateRow23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GCardRateRow23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GCardRateRow23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GCardCartRow1;
    private javax.swing.JButton GCardCartRow10;
    private javax.swing.JButton GCardCartRow11;
    private javax.swing.JButton GCardCartRow12;
    private javax.swing.JButton GCardCartRow13;
    private javax.swing.JButton GCardCartRow14;
    private javax.swing.JButton GCardCartRow15;
    private javax.swing.JButton GCardCartRow16;
    private javax.swing.JButton GCardCartRow17;
    private javax.swing.JButton GCardCartRow18;
    private javax.swing.JButton GCardCartRow19;
    private javax.swing.JButton GCardCartRow2;
    private javax.swing.JButton GCardCartRow20;
    private javax.swing.JButton GCardCartRow21;
    private javax.swing.JButton GCardCartRow22;
    private javax.swing.JButton GCardCartRow23;
    private javax.swing.JButton GCardCartRow3;
    private javax.swing.JButton GCardCartRow4;
    private javax.swing.JButton GCardCartRow5;
    private javax.swing.JButton GCardCartRow6;
    private javax.swing.JButton GCardCartRow7;
    private javax.swing.JButton GCardCartRow8;
    private javax.swing.JButton GCardCartRow9;
    private javax.swing.JPanel GCardPanel1;
    private javax.swing.JButton GCardRateRow1;
    private javax.swing.JButton GCardRateRow10;
    private javax.swing.JButton GCardRateRow11;
    private javax.swing.JButton GCardRateRow12;
    private javax.swing.JButton GCardRateRow13;
    private javax.swing.JButton GCardRateRow14;
    private javax.swing.JButton GCardRateRow15;
    private javax.swing.JButton GCardRateRow16;
    private javax.swing.JButton GCardRateRow17;
    private javax.swing.JButton GCardRateRow18;
    private javax.swing.JButton GCardRateRow19;
    private javax.swing.JButton GCardRateRow2;
    private javax.swing.JButton GCardRateRow20;
    private javax.swing.JButton GCardRateRow21;
    private javax.swing.JButton GCardRateRow22;
    private javax.swing.JButton GCardRateRow23;
    private javax.swing.JButton GCardRateRow3;
    private javax.swing.JButton GCardRateRow4;
    private javax.swing.JButton GCardRateRow5;
    private javax.swing.JButton GCardRateRow6;
    private javax.swing.JButton GCardRateRow7;
    private javax.swing.JButton GCardRateRow8;
    private javax.swing.JButton GCardRateRow9;
    private javax.swing.JScrollPane GCardcrollPane;
    private javax.swing.JTable jGCardTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
