/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonScrollPane = new javax.swing.JScrollPane();
        ButtonPanel = new javax.swing.JPanel();
        ComponentsPanel = new javax.swing.JPanel();
        ProcessorButton = new javax.swing.JButton();
        MotherBoardButton = new javax.swing.JButton();
        HardDiskButton = new javax.swing.JButton();
        PowerSupplyButton = new javax.swing.JButton();
        CasingButton = new javax.swing.JButton();
        RamButton = new javax.swing.JButton();
        GraphicsCardButton = new javax.swing.JButton();
        ProcessorLogo = new javax.swing.JLabel();
        MotherBoardLabel = new javax.swing.JLabel();
        RAMLogo = new javax.swing.JLabel();
        GraphicsCardLogo = new javax.swing.JLabel();
        HardDiskLogo = new javax.swing.JLabel();
        PowerSupplyLogo = new javax.swing.JLabel();
        CasingLogo = new javax.swing.JLabel();
        MPanel = new javax.swing.JPanel();
        MonitorButton = new javax.swing.JButton();
        L1Label = new javax.swing.JLabel();
        KPanel = new javax.swing.JPanel();
        KeyboardButton = new javax.swing.JButton();
        L1Label1 = new javax.swing.JLabel();
        MoPanel = new javax.swing.JPanel();
        MouseButton = new javax.swing.JButton();
        L1Label2 = new javax.swing.JLabel();
        SSPanel = new javax.swing.JPanel();
        SSButton = new javax.swing.JButton();
        L1Label3 = new javax.swing.JLabel();
        UpsPanel = new javax.swing.JPanel();
        UpsButton = new javax.swing.JButton();
        L1Label4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CPU_ComponentLabel = new javax.swing.JLabel();
        ArrowLogoLabel = new javax.swing.JLabel();
        SPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        ButtonPanel.setBackground(new java.awt.Color(153, 217, 234));

        ComponentsPanel.setBackground(new java.awt.Color(137, 180, 177));

        ProcessorButton.setBackground(new java.awt.Color(137, 180, 177));
        ProcessorButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ProcessorButton.setForeground(new java.awt.Color(51, 51, 51));
        ProcessorButton.setText("Processor");

        MotherBoardButton.setBackground(new java.awt.Color(137, 180, 177));
        MotherBoardButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MotherBoardButton.setForeground(new java.awt.Color(51, 51, 51));
        MotherBoardButton.setText("MotherBoard\n\n");

        HardDiskButton.setBackground(new java.awt.Color(137, 180, 177));
        HardDiskButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HardDiskButton.setForeground(new java.awt.Color(51, 51, 51));
        HardDiskButton.setText("Internal HDD");

        PowerSupplyButton.setBackground(new java.awt.Color(137, 180, 177));
        PowerSupplyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PowerSupplyButton.setForeground(new java.awt.Color(51, 51, 51));
        PowerSupplyButton.setText("Power Supply");
        PowerSupplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PowerSupplyButtonActionPerformed(evt);
            }
        });

        CasingButton.setBackground(new java.awt.Color(137, 180, 177));
        CasingButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CasingButton.setForeground(new java.awt.Color(51, 51, 51));
        CasingButton.setText("Casing");
        CasingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasingButtonActionPerformed(evt);
            }
        });

        RamButton.setBackground(new java.awt.Color(137, 180, 177));
        RamButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RamButton.setForeground(new java.awt.Color(51, 51, 51));
        RamButton.setText("RAM");

        GraphicsCardButton.setBackground(new java.awt.Color(137, 180, 177));
        GraphicsCardButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GraphicsCardButton.setForeground(new java.awt.Color(51, 51, 51));
        GraphicsCardButton.setText("Graphics Card\n");

        ProcessorLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Processor Logo.png"))); // NOI18N

        MotherBoardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MotherBoard Logo.png"))); // NOI18N

        RAMLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RAM Logo.png"))); // NOI18N

        GraphicsCardLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphics Card Logo.png"))); // NOI18N

        HardDiskLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HDD Logo.png"))); // NOI18N

        PowerSupplyLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Power Supply Logo.png"))); // NOI18N

        CasingLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Casing Logo.png"))); // NOI18N

        javax.swing.GroupLayout ComponentsPanelLayout = new javax.swing.GroupLayout(ComponentsPanel);
        ComponentsPanel.setLayout(ComponentsPanelLayout);
        ComponentsPanelLayout.setHorizontalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(ProcessorLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MotherBoardLabel))
                    .addComponent(RAMLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(GraphicsCardLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(HardDiskLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerSupplyLogo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CasingLogo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CasingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotherBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GraphicsCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HardDiskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerSupplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
        ComponentsPanelLayout.setVerticalGroup(
            ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ComponentsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProcessorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcessorLogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MotherBoardLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotherBoardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RAMLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GraphicsCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GraphicsCardLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HardDiskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HardDiskLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PowerSupplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PowerSupplyLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ComponentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CasingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CasingLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        MPanel.setBackground(new java.awt.Color(137, 180, 177));
        MPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MonitorButton.setBackground(new java.awt.Color(137, 180, 177));
        MonitorButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        MonitorButton.setForeground(new java.awt.Color(51, 51, 51));
        MonitorButton.setText("Monitor");
        MonitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitorButtonActionPerformed(evt);
            }
        });
        MPanel.add(MonitorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 220, 50));

        L1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monitor Logo.png"))); // NOI18N
        MPanel.add(L1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 50, 50));

        KPanel.setBackground(new java.awt.Color(137, 180, 177));

        KeyboardButton.setBackground(new java.awt.Color(137, 180, 177));
        KeyboardButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        KeyboardButton.setForeground(new java.awt.Color(51, 51, 51));
        KeyboardButton.setText("Keyboard");

        L1Label1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Keyboard Logo.png"))); // NOI18N

        javax.swing.GroupLayout KPanelLayout = new javax.swing.GroupLayout(KPanel);
        KPanel.setLayout(KPanelLayout);
        KPanelLayout.setHorizontalGroup(
            KPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L1Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KeyboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        KPanelLayout.setVerticalGroup(
            KPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(KPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KeyboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L1Label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        MoPanel.setBackground(new java.awt.Color(137, 180, 177));

        MouseButton.setBackground(new java.awt.Color(137, 180, 177));
        MouseButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        MouseButton.setForeground(new java.awt.Color(51, 51, 51));
        MouseButton.setText("Mouse");
        MouseButton.setBorderPainted(false);

        L1Label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mouse Logo.png"))); // NOI18N

        javax.swing.GroupLayout MoPanelLayout = new javax.swing.GroupLayout(MoPanel);
        MoPanel.setLayout(MoPanelLayout);
        MoPanelLayout.setHorizontalGroup(
            MoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MoPanelLayout.setVerticalGroup(
            MoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(L1Label2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        SSPanel.setBackground(new java.awt.Color(137, 180, 177));

        SSButton.setBackground(new java.awt.Color(137, 180, 177));
        SSButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        SSButton.setForeground(new java.awt.Color(51, 51, 51));
        SSButton.setText("Sound System");

        L1Label3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sound System Logo.png"))); // NOI18N

        javax.swing.GroupLayout SSPanelLayout = new javax.swing.GroupLayout(SSPanel);
        SSPanel.setLayout(SSPanelLayout);
        SSPanelLayout.setHorizontalGroup(
            SSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SSPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L1Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        SSPanelLayout.setVerticalGroup(
            SSPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(L1Label3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        UpsPanel.setBackground(new java.awt.Color(137, 180, 177));

        UpsButton.setBackground(new java.awt.Color(137, 180, 177));
        UpsButton.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        UpsButton.setForeground(new java.awt.Color(51, 51, 51));
        UpsButton.setText("UPS");

        L1Label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UPS Logo.png"))); // NOI18N

        javax.swing.GroupLayout UpsPanelLayout = new javax.swing.GroupLayout(UpsPanel);
        UpsPanel.setLayout(UpsPanelLayout);
        UpsPanelLayout.setHorizontalGroup(
            UpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(L1Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        UpsPanelLayout.setVerticalGroup(
            UpsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UpsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(L1Label4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setBackground(new java.awt.Color(137, 180, 177));

        CPU_ComponentLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        CPU_ComponentLabel.setForeground(new java.awt.Color(51, 51, 51));
        CPU_ComponentLabel.setText("CPU Components");

        ArrowLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arrow.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CPU_ComponentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ArrowLogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CPU_ComponentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ArrowLogoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SPanel.setBackground(new java.awt.Color(137, 180, 177));

        jButton1.setBackground(new java.awt.Color(137, 180, 177));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Suggestions");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SPanelLayout = new javax.swing.GroupLayout(SPanel);
        SPanel.setLayout(SPanelLayout);
        SPanelLayout.setHorizontalGroup(
            SPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SPanelLayout.setVerticalGroup(
            SPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ButtonPanelLayout = new javax.swing.GroupLayout(ButtonPanel);
        ButtonPanel.setLayout(ButtonPanelLayout);
        ButtonPanelLayout.setHorizontalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(KPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(MoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UpsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addComponent(MPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(SSPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        ButtonPanelLayout.setVerticalGroup(
            ButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComponentsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SSPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        ButtonScrollPane.setViewportView(ButtonPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(ButtonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ButtonScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PowerSupplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerSupplyButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerSupplyButtonActionPerformed

    private void CasingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasingButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CasingButtonActionPerformed

    private void MonitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonitorButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ArrowLogoLabel;
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JScrollPane ButtonScrollPane;
    private javax.swing.JLabel CPU_ComponentLabel;
    private javax.swing.JButton CasingButton;
    private javax.swing.JLabel CasingLogo;
    private javax.swing.JPanel ComponentsPanel;
    private javax.swing.JButton GraphicsCardButton;
    private javax.swing.JLabel GraphicsCardLogo;
    private javax.swing.JButton HardDiskButton;
    private javax.swing.JLabel HardDiskLogo;
    private javax.swing.JPanel KPanel;
    private javax.swing.JButton KeyboardButton;
    private javax.swing.JLabel L1Label;
    private javax.swing.JLabel L1Label1;
    private javax.swing.JLabel L1Label2;
    private javax.swing.JLabel L1Label3;
    private javax.swing.JLabel L1Label4;
    private javax.swing.JPanel MPanel;
    private javax.swing.JPanel MoPanel;
    private javax.swing.JButton MonitorButton;
    private javax.swing.JButton MotherBoardButton;
    private javax.swing.JLabel MotherBoardLabel;
    private javax.swing.JButton MouseButton;
    private javax.swing.JButton PowerSupplyButton;
    private javax.swing.JLabel PowerSupplyLogo;
    private javax.swing.JButton ProcessorButton;
    private javax.swing.JLabel ProcessorLogo;
    private javax.swing.JLabel RAMLogo;
    private javax.swing.JButton RamButton;
    private javax.swing.JPanel SPanel;
    private javax.swing.JButton SSButton;
    private javax.swing.JPanel SSPanel;
    private javax.swing.JButton UpsButton;
    private javax.swing.JPanel UpsPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
